version: '3'
services:
  app:
    image: mysql:5.7.12
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 設定を変更した時は ./data を消す必要がある時がある
      - ./data:/var/lib/mysql/
    ports:
      - 3306:3306

