services:
  app:
    image: postgres:16.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/
