version: '2'
services:
  postgres:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
